import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { randomUUID } from 'crypto';
import { Repository } from 'typeorm';
import { BusinessErrorCode, throwBusinessError } from '../../common/business-error';
import { CmsPageEntity } from '../../database/entities/cms-page.entity';
import { GeoAreaEntity } from '../../database/entities/geo-area.entity';
import { SearchIndexDocEntity } from '../../database/entities/search-index-doc.entity';

/** P1 FR-CNT-001 / FR-CNT-004 — CMS + programmatic SEO from master geo. */
@Injectable()
export class CmsService {
  constructor(
    @InjectRepository(GeoAreaEntity)
    private readonly areas: Repository<GeoAreaEntity>,
    @InjectRepository(CmsPageEntity)
    private readonly pages: Repository<CmsPageEntity>,
    @InjectRepository(SearchIndexDocEntity)
    private readonly indexDocs: Repository<SearchIndexDocEntity>,
  ) {}

  async listAreas(tenantId: string, city?: string) {
    const qb = this.areas
      .createQueryBuilder('a')
      .where('a.tenant_id = :tenantId', { tenantId })
      .orderBy('a.city', 'ASC')
      .addOrderBy('a.label', 'ASC');
    if (city?.trim()) qb.andWhere('a.city = :city', { city: city.trim() });
    const rows = await qb.getMany();
    return {
      data: rows.map((a) => ({
        id: a.id,
        slug: a.slug,
        label: a.label,
        city: a.city,
        level: a.level,
        seoTitle: a.seoTitle,
        seoDescription: a.seoDescription,
        listingCount: a.listingCount,
        isIndexable: a.isIndexable,
      })),
      meta: { count: rows.length, source: 'geo_master' },
    };
  }

  async getAreaLanding(tenantId: string, slug: string) {
    const area = await this.areas.findOne({ where: { tenantId, slug } });
    if (!area) throwBusinessError(BusinessErrorCode.NOT_FOUND, `Area ${slug} not found`);

    const listingCount = await this.indexDocs.count({
      where: { tenantId, district: area.label },
    });
    area.listingCount = listingCount;
    await this.areas.save(area);

    const indexable = listingCount >= 3;
    if (!indexable) {
      return {
        data: {
          area: this.mapArea(area),
          cmsBody: null,
          robots: 'noindex',
          thinPage: true,
        },
        meta: { listingCount, indexable: false },
      };
    }

    let page = await this.pages.findOne({
      where: { tenantId, geoAreaId: area.id, status: 'PUBLISHED' },
    });
    if (!page) {
      page = await this.pages.save({
        id: `cms_${randomUUID().replace(/-/g, '').slice(0, 8)}`,
        tenantId,
        slug: `mua-${area.slug}`,
        pageType: 'area',
        title: area.seoTitle ?? area.label,
        body: `<p>Khám phá ${listingCount} căn hộ Verified tại ${area.label}, ${area.city}. Giá Golden Record minh bạch.</p>`,
        status: 'PUBLISHED',
        geoAreaId: area.id,
        projectId: null,
        meta: { autoGenerated: true },
        publishedAt: new Date(),
      });
    }

    return {
      data: {
        area: this.mapArea(area),
        cms: {
          title: page.title,
          body: page.body,
          slug: page.slug,
          publishedAt: page.publishedAt?.toISOString(),
        },
        robots: 'index,follow',
        thinPage: false,
      },
      meta: { listingCount, indexable: true },
    };
  }

  async upsertPage(
    tenantId: string,
    input: {
      slug: string;
      pageType: CmsPageEntity['pageType'];
      title: string;
      body: string;
      geoAreaId?: string;
      projectId?: string;
      status?: CmsPageEntity['status'];
    },
  ) {
    let page = await this.pages.findOne({ where: { tenantId, slug: input.slug } });
    if (!page) {
      page = this.pages.create({
        id: `cms_${randomUUID().replace(/-/g, '').slice(0, 8)}`,
        tenantId,
        slug: input.slug,
        pageType: input.pageType,
        title: input.title,
        body: input.body,
        status: input.status ?? 'DRAFT',
        geoAreaId: input.geoAreaId ?? null,
        projectId: input.projectId ?? null,
        meta: null,
        publishedAt: input.status === 'PUBLISHED' ? new Date() : null,
      });
    } else {
      page.title = input.title;
      page.body = input.body;
      page.status = input.status ?? page.status;
      if (input.status === 'PUBLISHED' && !page.publishedAt) page.publishedAt = new Date();
    }
    await this.pages.save(page);
    return { data: page };
  }

  private mapArea(area: GeoAreaEntity) {
    return {
      id: area.id,
      slug: area.slug,
      label: area.label,
      city: area.city,
      seoTitle: area.seoTitle,
      seoDescription: area.seoDescription,
      listingCount: area.listingCount,
    };
  }
}
