"""Manual BA use-case details — Identity & Tenant P0 (UC-ID-01 … UC-ID-04)."""
from __future__ import annotations

from wereal_ba_detail_helpers import uc_detail

ID_USE_CASE_DETAILS: dict[str, dict] = {
    "UC-ID-01": uc_detail(
        "UC-ID-01",
        "Onboarding tenant Developer/Agency",
        screens="SCR-ADMIN-019",
        actor="Platform Admin",
        actor_secondary="System (RLS schema, default roles seed)",
        goal="Tenant mới active với isolation RLS + default RBAC — pilot CON-13",
        trigger="Platform Admin onboard Developer hoặc Agency sau hợp đồng",
        pre="cap platform.tenants.create; slug unique",
        post="Tenant ACTIVE; admin invite sent; RLS policies applied",
        priority="P0 Must",
        trace="FR-ID-01 · BR-25, CON-13",
        api="POST /tenants · POST /users invite · POST /tenants/{id}/activate",
        prototype="/admin/tenants/onboard · /uc/UC-ID-01",
        main=[
            [1, "Wizard step 1: tenant type DEVELOPER | AGENCY, legal name, slug"],
            [2, "Step 2: subscription plan, module flags Phase 1 scope"],
            [3, "Step 3: seed default roles (Developer Admin, Agent, Ops…) FR-ID-02"],
            [4, "POST /tenants → tenantId; provision RLS tenant_id column policies"],
            [5, "Invite primary admin email — magic link set password"],
            [6, "Activate → pilot checklist UAT BR-25; appear tenant switcher"],
        ],
        alt=[
            ["E1", "Duplicate slug → 409 suggest suffix"],
            ["E2", "Activate without admin verified → block go-live gate"],
        ],
        io_in="tenantType, name, slug, planId, adminEmail, modules[]",
        io_out="tenantId, status ACTIVE, defaultRoleIds[], audit",
        rules=["BR-25"],
    ),
    "UC-ID-02": uc_detail(
        "UC-ID-02",
        "Phân quyền user theo role/project",
        screens="SCR-ADMIN-021",
        actor="Agency Admin, Developer Admin",
        actor_secondary="Platform Admin (cross-tenant templates)",
        goal="RBAC + ABAC project scope — Agency không write GR price",
        trigger="Admin cấu hình role permissions hoặc gán user",
        pre="Tenant active; cap iam.roles.manage",
        post="Policy saved; effective permissions cached; audit",
        priority="P0 Must",
        trace="FR-ID-02 · BR-01, CON-09",
        api="GET/PATCH /roles · POST policy bindings · ABAC projectId",
        prototype="/admin/users/roles · /uc/UC-ID-02",
        main=[
            [1, "Role list: built-in + custom tenant roles"],
            [2, "Permission matrix: module × action (read/write/admin)"],
            [3, "ABAC tab: restrict role to projectIds[] — Developer sales team"],
            [4, "Deny override gr.units.write for AGENT role CON-09"],
            [5, "Preview effective caps for test user"],
            [6, "Save → invalidate JWT permission cache ≤60s"],
        ],
        alt=[
            ["E1", "Remove last Admin role → block save"],
            ["E2", "Platform template push → tenant opt-in merge"],
        ],
        io_in="roleId, permissions[], projectScope[], denyRules[]",
        io_out="policyVersion, effectiveMatrix preview",
        rules=["BR-01"],
    ),
    "UC-ID-03": uc_detail(
        "UC-ID-03",
        "Đăng nhập, refresh token & MFA",
        screens="SCR-AUTH-001",
        actor="All users (all portals)",
        actor_secondary="System (token rotation, brute-force guard)",
        goal="Secure auth JWT 15min + refresh 7d; MFA step-up for payment BR-14",
        trigger="User navigate protected route or explicit login",
        pre="Account ACTIVE; tenant context if multi-org",
        post="accessToken + refreshToken; tenant_id in claims; redirect portal home",
        priority="P0 Must",
        trace="FR-ID-04 · BR-14, CON-10",
        api="POST /auth/login · POST /auth/refresh · POST /auth/mfa/verify",
        prototype="/auth/login · /uc/UC-ID-03",
        main=[
            [1, "Login form: email, password, tenant selector if multi-tenant"],
            [2, "POST /auth/login — rate limit 10/min/IP; audit attempt"],
            [3, "Success → store refresh httpOnly cookie; access in memory"],
            [4, "Silent refresh before access expiry via POST /auth/refresh rotate"],
            [5, "Sensitive action (payment) → MFA OTP modal step-up BR-14"],
            [6, "Redirect by role: /developer | /agent | /admin | /buyer | /finance"],
        ],
        alt=[
            ["E1", "5 failed attempts → 423 lock 15min"],
            ["E2", "Refresh reuse detected → revoke family force re-login"],
            ["E3", "MFA wrong 3x → lock sensitive ops 15min"],
        ],
        io_in="email, password, tenantId?, mfaOtp?, refreshToken",
        io_out="tokens, user profile, tenant context, audit login",
        rules=["BR-14"],
    ),
    "UC-ID-04": uc_detail(
        "UC-ID-04",
        "Quản lý user trong tenant",
        screens="SCR-ADMIN-020",
        actor="Agency Admin, Developer Admin",
        actor_secondary="System (invite email, deactivation cascade)",
        goal="Invite/deactivate users; assign roles; không share credentials",
        trigger="Admin thêm nhân viên hoặc offboard",
        pre="cap iam.users.manage; seat limit plan quota",
        post="User INVITED|ACTIVE|DEACTIVATED; role bindings updated",
        priority="P0 Must",
        trace="FR-ID-02",
        api="GET/POST /users · PATCH /users/{id} · POST invite/resend",
        prototype="/admin/users · /uc/UC-ID-04",
        main=[
            [1, "User table: name, email, role, status, last login"],
            [2, "Invite user modal: email + role + optional project ABAC"],
            [3, "POST invite → email magic link 48h expiry"],
            [4, "Edit role assignment — không edit email directly P1"],
            [5, "Deactivate → revoke sessions; reassign open leads"],
            [6, "Audit log per user lifecycle event FR-TR-01"],
        ],
        alt=[
            ["E1", "Seat limit exceeded → upsell prompt"],
            ["E2", "Deactivate self last admin → blocked"],
        ],
        io_in="email, roleId, projectIds[], action INVITE|DEACTIVATE",
        io_out="userId, status, inviteToken metadata, audit",
        rules=["BR-08"],
    ),
}
