"""Deep SCR UI/API overrides — P0 Golden Record, Booking, Payment."""
from __future__ import annotations

from wereal_ba_detail_helpers import scr_detail

P0_SCREEN_DETAILS: dict[str, dict] = {
    "SCR-DEV-012": scr_detail(
        "SCR-DEV-012",
        "Bảng hàng Golden Record (Unit grid)",
        route="/developer/units",
        module="MOD-GR — Golden Record",
        purpose="Developer quản lý unit gốc — giá, diện tích, trạng thái tồn kho theo project",
        roles="Developer Admin",
        linked_ucs="UC-GR-01",
        app="Portal Chủ đầu tư (Developer)",
        trace="FR-GR-01, FR-GR-02",
        api="GET/PATCH /api/v1/units · GET /units/{id}/versions · GET /projects",
        pre="cap gr.units.read/write; ABAC projectId scope",
        post="Grid reflects latest GR version; audit trail accessible",
        notes="PremiumShell sidebar · KPI strip absorption preview",
        ui=[
            [1, "DeveloperSidebar", "Navigation", "Có", "Tổng quan · GR · Product Graph · Import"],
            [2, "ProjectSelector", "Select", "Có", "Dropdown project tenant — ABAC filter"],
            [3, "UnitKpiStrip", "KPI", "Có", "Total / Available / Reserved / Sold"],
            [4, "UnitGrid", "DataGrid", "Có", "Columns: mã căn, tầng, diện tích, giá, status, version"],
            [5, "InlinePriceEditor", "CellEditor", "Có", "PATCH optimistic lock — Developer only"],
            [6, "StatusChip", "Badge", "Có", "AVAILABLE | RESERVED | SOLD | HOLD — color coded"],
            [7, "AuditDrawer", "Drawer", "Có", "Version history + actor timeline"],
            [8, "BulkActionsBar", "Toolbar", "Không", "P2: export selection · link import"],
        ],
        rules=["BR-01", "BR-08", "BR-20"],
    ),
    "SCR-DEV-010": scr_detail(
        "SCR-DEV-010",
        "Product Graph — quan hệ unit",
        route="/developer/product-graph",
        module="MOD-GR — Golden Record",
        purpose="Visualize Project → Building → Floor → Unit hierarchy",
        roles="Developer Admin",
        linked_ucs="UC-GR-04",
        app="Portal Chủ đầu tư (Developer)",
        trace="FR-GR-01",
        api="GET /projects/{id}/graph",
        ui=[
            [1, "GraphCanvas", "Graph", "Có", "Force/tree layout — zoom/pan"],
            [2, "NodeTooltip", "Popover", "Có", "Unit summary on hover"],
            [3, "AbsorptionLegend", "Legend", "Có", "Color scale sold %"],
            [4, "GraphFilters", "Filter", "Có", "Tower, status, price band"],
            [5, "DeepLinkCTA", "Link", "Có", "Click unit → /developer/units?unitId="],
        ],
        rules=["BR-01"],
    ),
    "SCR-AGENT-011": scr_detail(
        "SCR-AGENT-011",
        "Listing Wizard — tạo tin từ GR",
        route="/agent/listings/new",
        module="MOD-GR + MOD-LS",
        purpose="Wizard 3-step: chọn unit GR → marketing copy/media → anti-drift submit",
        roles="Agent",
        linked_ucs="UC-GR-02, UC-AI-01",
        app="Agent Portal",
        trace="FR-GR-03, FR-GR-04, FR-LS-03",
        api="POST /listings · POST /listings/drift-check · POST /ai/listing-copy",
        ui=[
            [1, "WizardStepper", "Stepper", "Có", "3 steps: Unit · Content · Review"],
            [2, "UnitSearchPanel", "Search", "Có", "Search GR units eligible — SSE status"],
            [3, "GrSnapshotReadonly", "Panel", "Có", "Giá/m²/pháp lý read-only từ GR"],
            [4, "MarketingForm", "Form", "Có", "Title, description, highlights"],
            [5, "AiCopilotPanel", "AI", "Không", "Generate copy + disclaimer BR-16"],
            [6, "MediaUploadZone", "Upload", "Có", "Presigned S3 — UC-LS-04"],
            [7, "DriftCheckPanel", "Alert", "Có", "PASS/WARN/BLOCK before submit"],
            [8, "SubmitForReview", "Button", "Có", "→ PENDING_REVIEW queue"],
        ],
        rules=["BR-01", "BR-06", "BR-09", "BR-16"],
    ),
    "SCR-ADMIN-016": scr_detail(
        "SCR-ADMIN-016",
        "Moderation Queue — anti-drift & publish",
        route="/admin/moderation",
        module="MOD-GR + MOD-LS",
        purpose="Ops duyệt listing: drift check, verified badge, publish OpenSearch",
        roles="Ops Admin, Platform Admin",
        linked_ucs="UC-GR-03, UC-LS-02",
        app="Admin / Ops Portal",
        trace="FR-GR-04, FR-GR-05, FR-LS-01",
        api="GET /moderation/queue · POST /listings/{id}/approve|reject",
        ui=[
            [1, "ModerationQueueTable", "Table", "Có", "Filter: PENDING, DRIFT_FLAG, duplicate"],
            [2, "SplitCompareView", "Panel", "Có", "GR vs Listing side-by-side"],
            [3, "DriftSeverityBadge", "Badge", "Có", "BLOCK red · WARN amber"],
            [4, "PublicPreviewIframe", "Preview", "Có", "Verified badge mock BR-10"],
            [5, "ApproveRejectBar", "Toolbar", "Có", "Reject reason required"],
            [6, "BulkModeration", "Checkbox", "Không", "Batch ≤20 same project"],
        ],
        rules=["BR-09", "BR-10", "BR-01", "BR-08"],
    ),
    "SCR-SYS-002": scr_detail(
        "SCR-SYS-002",
        "SSE Unit Status Broker (system)",
        route="/uc/UC-GR-07",
        module="MOD-GR — Infrastructure",
        purpose="Real-time unit status push ≤5s — no primary UI",
        roles="System, DevOps monitor",
        linked_ucs="UC-GR-07",
        app="NestJS SSE Gateway + Redis pub/sub",
        trace="FR-GR-08, FR-LS-06",
        api="GET /sse/units · internal outbox consumer",
        status_note="Draft — infra component",
        ui=[
            [1, "SseHealthDashboard", "Monitor", "Có", "Connections count, p95 latency"],
            [2, "EventStreamLog", "Log", "Có", "Last 100 events tenant-scoped"],
            [3, "ChannelMetrics", "Chart", "Không", "Redis pub/sub throughput"],
        ],
        rules=["BR-20", "BR-03"],
    ),
    "SCR-AGENT-005": scr_detail(
        "SCR-AGENT-005",
        "Tạo booking / giữ chỗ",
        route="/agent/bookings/new",
        module="MOD-BK — Booking",
        purpose="Agent tạo booking atomic lock với expiry countdown",
        roles="Agent",
        linked_ucs="UC-BK-01",
        app="Agent Portal",
        trace="FR-BK-01, FR-BK-02",
        api="POST /api/v1/bookings · Idempotency-Key header",
        ui=[
            [1, "LeadSelector", "Combobox", "Có", "Search pipeline leads"],
            [2, "UnitSelector", "Search", "Có", "GR/search — live status SSE"],
            [3, "DepositAmountInput", "Currency", "Có", "VND tabular nums · min deposit rule"],
            [4, "ExpirySelector", "Select", "Có", "Default 48h · max 72h"],
            [5, "AtomicLockIndicator", "Alert", "Có", "Spinner during POST — prevent double click"],
            [6, "BookingSuccessCard", "Card", "Có", "Ref, expiresAt, copy payment link"],
        ],
        rules=["BR-02", "BR-03", "BR-17"],
    ),
    "SCR-AGENT-003": scr_detail(
        "SCR-AGENT-003",
        "Booking detail — event timeline",
        route="/agent/bookings/bk_018",
        module="MOD-BK — Booking",
        purpose="Domain event timeline cho booking — ops & dispute evidence",
        roles="Agent, Ops Admin",
        linked_ucs="UC-BK-03",
        app="Agent Portal",
        trace="FR-BK-04",
        api="GET /bookings/{id}/timeline · GET /bookings/{id}/events",
        ui=[
            [1, "BookingHeader", "Header", "Có", "Ref, status chip, expiry countdown"],
            [2, "StateStepperCompact", "Stepper", "Có", "Mini 15-state overview"],
            [3, "EventTimeline", "Timeline", "Có", "Actor, timestamp, payload summary"],
            [4, "EventFilterTabs", "Tabs", "Có", "All · State · Payment · System"],
            [5, "ExportTimeline", "Button", "Không", "CSV/PDF P2 dispute pack"],
            [6, "LinkedPayments", "Link", "Có", "Jump Finance reconcile"],
        ],
        rules=["BR-08", "BR-24"],
    ),
    "SCR-AGENT-004": scr_detail(
        "SCR-AGENT-004",
        "Hủy booking & kích hoạt refund",
        route="/agent/bookings/cancel",
        module="MOD-BK + MOD-PAY",
        purpose="Cancel workflow với reason, MFA nếu đã cọc, handoff refund",
        roles="Agent",
        linked_ucs="UC-BK-05",
        app="Agent Portal",
        trace="FR-BK-07",
        api="DELETE /bookings/{id} · POST /refunds",
        ui=[
            [1, "CancelSummary", "Panel", "Có", "Deposit paid, refund estimate"],
            [2, "CancelReasonSelect", "Select", "Có", "Enum reasons — required"],
            [3, "MfaOtpModal", "Modal", "Có", "If deposit SUCCEEDED BR-14"],
            [4, "ConfirmCancel", "Button", "Có", "Destructive confirm"],
            [5, "RefundStatusTracker", "Stepper", "Không", "Links UC-PAY-03 status"],
        ],
        rules=["BR-22", "BR-14", "BR-03"],
    ),
    "SCR-BUYER-002": scr_detail(
        "SCR-BUYER-002",
        "Buyer Deal Tracker",
        route="/buyer/deals",
        module="MOD-BK — Buyer experience",
        purpose="Buyer theo dõi booking 15-state + CTA thanh toán",
        roles="Buyer",
        linked_ucs="UC-BK-02, UC-UX-02",
        app="Buyer Portal",
        trace="FR-BK-03, FR-UX-06",
        api="GET /bff/buyer/deals · GET /bookings/{id}",
        ui=[
            [1, "DealListCards", "CardList", "Có", "Active bookings summary"],
            [2, "DealStepper15", "Stepper", "Có", "Full vertical stepper tiếng Việt"],
            [3, "PayDepositCTA", "Button", "Có", "→ /buyer/payment when DEPOSIT_PENDING"],
            [4, "SupportChatLink", "Link", "Không", "Contact agent"],
            [5, "NotificationBell", "Icon", "Không", "P2 push status changes"],
        ],
        rules=["BR-02", "BR-08"],
    ),
    "SCR-BUYER-004": scr_detail(
        "SCR-BUYER-004",
        "Thanh toán cọc online",
        route="/buyer/payment",
        module="MOD-PAY — Payment",
        purpose="Payment intent + VNPay QR/redirect + MFA OTP",
        roles="Buyer",
        linked_ucs="UC-PAY-01",
        app="Buyer Portal",
        trace="FR-PAY-01, FR-PAY-05",
        api="POST /payment-intents · POST /webhooks/payment",
        ui=[
            [1, "PaymentSummary", "Panel", "Có", "Amount, booking ref, project name"],
            [2, "MfaOtpInput", "Form", "Có", "6-digit OTP before gateway BR-14"],
            [3, "VnpayQrPanel", "QR", "Có", "QR code + countdown 15min"],
            [4, "RedirectFallback", "Link", "Có", "Open VNPay in new tab"],
            [5, "PaymentStatusPoller", "Spinner", "Có", "Poll until SUCCEEDED/FAILED"],
            [6, "ReceiptDownload", "Link", "Có", "On success — PDF receipt"],
        ],
        rules=["BR-02", "BR-11", "BR-14", "BR-21", "BR-18"],
    ),
    "SCR-FIN-004": scr_detail(
        "SCR-FIN-004",
        "Đối soát thanh toán hàng ngày",
        route="/finance/reconciliation",
        module="MOD-PAY — Finance",
        purpose="Gateway vs ledger daily match — discrepancy workflow",
        roles="Finance Admin",
        linked_ucs="UC-PAY-02",
        app="Finance Portal",
        trace="FR-PAY-04",
        api="GET /finance/reconciliation · POST /reconciliation/run",
        ui=[
            [1, "BusinessDatePicker", "Date", "Có", "Select reconcile date D"],
            [2, "MatchRateKpi", "KPI", "Có", "Green 100% · red otherwise"],
            [3, "ReconciliationTable", "Table", "Có", "gatewayRef, ledgerId, amount, delta"],
            [4, "DiscrepancyPanel", "Alert", "Có", "Assign owner + comment"],
            [5, "RunReconcileButton", "Button", "Có", "Manual trigger batch"],
            [6, "ExportCsv", "Button", "Có", "Download report BR-04"],
        ],
        rules=["BR-04", "BR-11", "BR-18", "BR-21"],
    ),
    "SCR-FIN-005": scr_detail(
        "SCR-FIN-005",
        "Refund & ledger reversal",
        route="/finance/refunds",
        module="MOD-PAY — Finance",
        purpose="Process refunds idempotent với double-entry reversal",
        roles="Finance Admin",
        linked_ucs="UC-PAY-03",
        app="Finance Portal",
        trace="FR-PAY-02",
        api="POST /refunds · GET /refunds?status=PENDING",
        ui=[
            [1, "RefundQueueTable", "Table", "Có", "From booking cancels + manual"],
            [2, "RefundDetailDrawer", "Drawer", "Có", "Original payment, amount, timeline"],
            [3, "MfaConfirmModal", "Modal", "Có", "Finance MFA BR-14"],
            [4, "LedgerReversalPreview", "Table", "Có", "Debit/credit lines preview BR-18"],
            [5, "ProcessRefundButton", "Button", "Có", "Trigger gateway + ledger"],
            [6, "RefundStatusBadge", "Badge", "Có", "PENDING | PROCESSING | SUCCEEDED | FAILED"],
        ],
        rules=["BR-18", "BR-22", "BR-21", "BR-14"],
    ),
}
