"""Manual BA use-case details — CRM P0 (UC-CRM-01 … UC-CRM-03)."""
from __future__ import annotations

from wereal_ba_detail_helpers import uc_detail

CRM_USE_CASE_DETAILS: dict[str, dict] = {
    "UC-CRM-01": uc_detail(
        "UC-CRM-01",
        "Gửi yêu cầu tư vấn (lead form)",
        screens="SCR-PUBLIC-006",
        actor="Buyer, Guest (P4 Thu Trang)",
        actor_secondary="System (routing engine, AI score UC-AI-02)",
        goal="Capture lead ≤3 click từ unit detail — consent PDPA đầy đủ",
        trigger="Buyer click «Nhận tư vấn» trên trang unit/listing",
        pre="Unit/listing PUBLISHED; form sticky visible; rate limit public API",
        post="Lead NEW created; consent logged; routing PENDING; thank-you screen",
        priority="P0 Must",
        trace="FR-CRM-01, FR-CRM-02 · BR-15",
        api="POST /api/v1/leads · Idempotency-Key · POST /ai/leads/{id}/score async",
        prototype="/public/units/un_01 · /uc/UC-CRM-01",
        main=[
            [1, "Buyer scroll unit detail — sticky LeadForm bottom (mobile) / sidebar (desktop)"],
            [2, "Nhập name, phone, email (optional), message — prefill unitId/listingId hidden"],
            [3, "Checkbox consent PDPA bắt buộc + link privacy policy version BR-15"],
            [4, "Submit POST /leads với UTM cookies nếu có — Idempotency tránh double submit"],
            [5, "201 → ThankYou modal + SLA «Agent liên hệ trong 15 phút»"],
            [6, "Async: AI score UC-AI-02 + routing UC-CRM-02 — notify agent HOT tier"],
        ],
        alt=[
            ["E1", "Consent unchecked → 422 inline error, không gửi"],
            ["E2", "Duplicate phone 24h → merge/link existing lead policy"],
            ["E3", "Spam honeypot field filled → silent drop + audit"],
        ],
        io_in="fullName, phone, email, unitId, listingId, message, consent{}, utm{}",
        io_out="leadId, status NEW, routingStatus PENDING, consent audit record",
        rules=["BR-15", "BR-07"],
    ),
    "UC-CRM-02": uc_detail(
        "UC-CRM-02",
        "Phân công lead cho agent (routing)",
        screens="SCR-AGENT-015",
        actor="Agency Admin (P2 Lan Hương)",
        actor_secondary="System (round-robin, AI HOT override)",
        goal="Mọi lead có owner primary trong SLA — HOT lead ưu tiên BR-07",
        trigger="Lead created hoặc Admin cấu hình/sửa routing rules",
        pre="cap crm.routing.manage; ≥1 active agent trong pool",
        post="Rules saved; new leads auto-assigned; audit rule version",
        priority="P0 Must",
        trace="FR-CRM-03 · BR-07",
        api="GET/PATCH /crm/routing-rules · POST /leads/{id}/assign",
        prototype="/agent/settings/routing · /uc/UC-CRM-02",
        main=[
            [1, "Agency Admin mở RoutingSettings — xem pools theo project/zone"],
            [2, "Cấu hình round-robin | territory | skill tags"],
            [3, "HOT tier rule: score ≥80 → bypass round-robin assign senior agent"],
            [4, "Save rules → version bump; áp dụng lead PENDING routing"],
            [5, "Manual reassign drag-drop trên lead list (override)"],
            [6, "Metrics: avg time-to-assign, SLA breach count dashboard"],
        ],
        alt=[
            ["E1", "No agent available → fallback Agency Admin queue"],
            ["E2", "Agent deactivated mid-rule → redistribute unassigned leads"],
        ],
        io_in="poolId, strategy, agentIds[], hotScoreThreshold, projectScope",
        io_out="routingRuleVersion, assignment events, notifications",
        rules=["BR-07"],
    ),
    "UC-CRM-03": uc_detail(
        "UC-CRM-03",
        "Quản lý pipeline & CRM activities",
        screens="SCR-AGENT-014",
        actor="Agent (P3 Hoàng Nam)",
        actor_secondary="System (activity sync, SLA timer P2)",
        goal="Agent quản lý lead→viewing→booking trên kanban nhanh hơn Zalo BR-12",
        trigger="Agent mở pipeline sau nhận lead assigned",
        pre="cap crm.pipeline.view; lead assigned to self or team",
        post="Stage updated; activity logged; timeline đồng bộ booking nếu có",
        priority="P0 Must",
        trace="FR-CRM-04, FR-CRM-05 · BR-12, BR-07",
        api="GET /leads · PATCH /leads/{id} · POST activities · Kanban BFF",
        prototype="/agent/pipeline · /uc/UC-CRM-03",
        main=[
            [1, "Kanban columns: NEW → CONTACTED → VIEWING → NEGOTIATING → BOOKING → WON/LOST"],
            [2, "Card hiển thị HOT badge, unit interest, last activity, SLA countdown"],
            [3, "Drag card → PATCH stage — validate allowed transitions"],
            [4, "Quick log: call / Zalo / visit — POST activity với geo optional P2"],
            [5, "Click card → drawer lead detail + link UC-BK-01 create booking"],
            [6, "Filter: my leads | hot | project | overdue SLA"],
        ],
        alt=[
            ["E1", "Move to BOOKING without unit → prompt select unit GR"],
            ["E2", "LOST requires reason enum — KPI tracking"],
            ["E3", "Concurrent drag → optimistic lock refresh"],
        ],
        io_in="leadId, stage, activity{type, note, duration}, bookingId?",
        io_out="updated lead, activity record, pipeline metrics",
        rules=["BR-12", "BR-07", "BR-08"],
    ),
}
