"""Manual BA use-case details — Commission COM (UC-COM-01 … UC-COM-05)."""
from __future__ import annotations

from wereal_ba_detail_helpers import uc_detail

COM_USE_CASE_DETAILS: dict[str, dict] = {
    "UC-COM-01": uc_detail(
        "UC-COM-01",
        "Cấu hình commission policy theo project",
        screens="SCR-DEV-004",
        actor="Developer Admin (P1 Minh Tuấn)",
        actor_secondary="Finance Admin (review publish P2)",
        goal="Developer định nghĩa tỷ lệ HH theo project — versioned, không retroactive BR-13",
        trigger="Developer mở Commission Policy sau go-live project hoặc đổi chính sách phân phối",
        pre="cap com.policy.manage; project ACTIVE; KYC developer verified (P2 BR-23)",
        post="Policy DRAFT hoặc PUBLISHED; version bump; audit actor + diff",
        priority="P1 Must",
        phase="Phase 2",
        trace="FR-COM-01 · BR-13, BR-19",
        api="GET/POST/PATCH /commission/policies · POST /policies/{id}/publish",
        prototype="/developer/commission · /uc/UC-COM-01",
        main=[
            [1, "Developer chọn project — xem policy ACTIVE hiện tại + history versions"],
            [2, "Tạo policy mới: base rate %, tier theo doanh số, agency split template"],
            [3, "Cấu hình split rules: primary agent %, co-agent %, agency % — validate sum ≤100%"],
            [4, "Effective date + optional sunset; holdback % default cho dispute BR holdback link"],
            [5, "Save DRAFT — preview impact trên deal mẫu (simulation read-only)"],
            [6, "Publish → confirmation modal «Không ảnh hưởng deal đã chốt» BR-13"],
            [7, "POST publish → status PUBLISHED; notify Finance + agencies affected"],
        ],
        alt=[
            ["E1", "Split % sum > 100 → 422 inline field errors"],
            ["E2", "Publish overlap effective dates → merge warning + require explicit override"],
            ["E3", "Agency không trong distribution policy → block publish BR-19"],
        ],
        io_in="projectId, baseRate, tiers[], splitRules[], effectiveFrom, holdbackRate",
        io_out="policyId, version, status PUBLISHED, auditEventId",
        rules=["BR-13", "BR-19", "BR-08"],
    ),
    "UC-COM-02": uc_detail(
        "UC-COM-02",
        "Snapshot policy tại thời điểm chốt deal",
        screens="SCR-SYS-001",
        actor="System (Booking/Deal completion handler)",
        actor_secondary="Finance Admin (read-only verify)",
        goal="Immutable commission policy snapshot gắn dealId — tranh chấp HH dùng bản frozen BR-13",
        trigger="Booking transition → COMPLETED hoặc CONTRACT_SIGNED per state machine",
        pre="Deal completed event emitted; active PUBLISHED policy exists for project at timestamp T",
        post="commissionPolicySnapshot stored; commission lines calculable; audit COM_SNAPSHOT_CREATED",
        priority="P0 Must",
        phase="Phase 1–2",
        trace="FR-COM-02 · BR-13, BR-24",
        api="Internal: CommissionSnapshotService.onDealCompleted · GET /deals/{id}/commission-snapshot",
        prototype="/uc/UC-COM-02",
        main=[
            [1, "DealCompleted domain event → CommissionSnapshotService consumer"],
            [2, "Resolve policy: latest PUBLISHED where effectiveFrom ≤ deal.closedAt"],
            [3, "Copy policy JSON + version + hash SHA-256 vào snapshot store (append-only)"],
            [4, "Link snapshotId to bookingId/dealId — foreign immutable"],
            [5, "Emit CommissionSnapshotCreated → trigger calculation queue UC-COM-03"],
            [6, "Finance có thể GET snapshot read-only — không PATCH allowed"],
        ],
        alt=[
            ["E1", "No policy at T → block deal complete OR fallback platform default + incident"],
            ["E2", "Duplicate event idempotent → return existing snapshotId"],
            ["E3", "Policy mid-publish race → lock policy row SELECT FOR UPDATE"],
        ],
        io_in="dealId, bookingId, closedAt, projectId, policyVersionHint",
        io_out="snapshotId, policyHash, linesPreview[], auditEventId",
        rules=["BR-13", "BR-24", "BR-08"],
    ),
    "UC-COM-03": uc_detail(
        "UC-COM-03",
        "Split commission nhiều agent/agency",
        screens="SCR-FIN-002",
        actor="Finance Admin (P6 Kim Anh)",
        actor_secondary="System (calc engine from snapshot UC-COM-02)",
        goal="Phân bổ HH theo snapshot — tổng 100%; queue settlement batch",
        trigger="Commission snapshot created hoặc Finance mở split review queue",
        pre="cap finance.commission.manage; snapshot exists; KYC agents BR-23",
        post="Commission lines APPROVED → settlement batch PENDING; ledger accrual optional P2",
        priority="P1 Must",
        phase="Phase 2",
        trace="FR-COM-03 · BR-13, BR-23",
        api="GET /finance/commission/splits · POST /commission/lines/{id}/approve",
        prototype="/finance/commission/split · /uc/UC-COM-03",
        main=[
            [1, "Finance mở Split Queue — filter deal closed period, project, agency"],
            [2, "Mỗi row: deal ref, snapshot version, gross commission, split breakdown"],
            [3, "Engine apply snapshot rules → lines per agent/agency/platform fee"],
            [4, "Validate sum = 100% gross; flag manual adjustment if rounding ±1 VND"],
            [5, "Finance review — override line requires dual approval + reason audit"],
            [6, "Approve batch → settlementRunId; export preview UC-COM-05"],
        ],
        alt=[
            ["E1", "Agent KYC incomplete → line ON_HOLD until UC-ID-05 pass BR-23"],
            ["E2", "Dispute open UC-TR-03 → auto holdback UC-COM-04 on affected lines"],
            ["E3", "Snapshot missing → block approve; escalate Tech"],
        ],
        io_in="dealIds[], period, adjustmentReason?, dualApproverId",
        io_out="commissionLineIds[], settlementRunId, holdbackFlags[]",
        rules=["BR-13", "BR-23", "BR-08"],
    ),
    "UC-COM-04": uc_detail(
        "UC-COM-04",
        "Holdback khi tranh chấp",
        screens="SCR-ADMIN-007",
        actor="Ops Admin (P5 Quốc Bảo)",
        actor_secondary="Finance Admin (release payout)",
        goal="Giữ HH khi dispute mở — release khi UC-TR-03 resolved BR-08",
        trigger="Dispute OPENED linked to booking/deal hoặc Ops manual hold",
        pre="cap com.holdback.manage; commission lines exist or accrual pending",
        post="Lines HELD; payout blocked; release audit on dispute close",
        priority="P1 Must",
        phase="Phase 2–3",
        trace="FR-COM-04, FR-TR-03 · BR-08, BR-13",
        api="POST /commission/holdback · POST /holdback/{id}/release",
        prototype="/admin/commission/holdback · /uc/UC-COM-04",
        main=[
            [1, "Ops mở Holdback Console — disputes OPEN + linked commission lines"],
            [2, "Select dispute → auto-suggest lines by bookingId/dealId graph"],
            [3, "Apply hold: percent or full amount; reason code required"],
            [4, "Notify Finance + agents — payout queue frozen for held lines"],
            [5, "Dispute RESOLVED → Ops review release partial/full per mediation outcome"],
            [6, "POST release → lines return APPROVED; settlement batch updated"],
        ],
        alt=[
            ["E1", "Release without resolved dispute → 403 unless Legal override role"],
            ["E2", "Partial release split → two child line records audit trail"],
        ],
        io_in="disputeId, commissionLineIds[], holdPercent, reasonCode",
        io_out="holdbackId, heldAmount, releaseEventId",
        rules=["BR-08", "BR-13", "BR-24"],
    ),
    "UC-COM-05": uc_detail(
        "UC-COM-05",
        "Export báo cáo hoa hồng kế toán",
        screens="SCR-FIN-001",
        actor="Finance Admin",
        actor_secondary="Developer Admin (read own project export P2)",
        goal="Export Excel/CSV chuẩn kế toán — mọi export logged BR-08",
        trigger="Finance chọn kỳ settlement closed hoặc month-end close",
        pre="cap finance.commission.export; settlement run COMPLETED or APPROVED lines",
        post="File generated + download URL expiring; export audit with row count hash",
        priority="P1 Should",
        phase="Phase 2",
        trace="FR-COM-05 · BR-08, BR-04",
        api="POST /finance/commission/export · GET /exports/{id}/download",
        prototype="/finance/commission/export · /uc/UC-COM-05",
        main=[
            [1, "Finance chọn period, project filter, format XLSX|CSV"],
            [2, "Preview columns: dealId, agent, agency, gross, net, tax code placeholder"],
            [3, "Include snapshot version + policy hash column for audit"],
            [4, "Generate async job — email link when >5000 rows"],
            [5, "Download — watermark tenantId + exportedBy + timestamp"],
            [6, "Audit EXPORT_COMMISSION_REPORT với file checksum"],
        ],
        alt=[
            ["E1", "Period not closed → warn + require confirm override"],
            ["E2", "Held lines included as separate sheet «Holdback»"],
        ],
        io_in="periodFrom, periodTo, projectIds[], format, includeHoldback",
        io_out="exportId, downloadUrl, rowCount, checksum",
        rules=["BR-08", "BR-04", "BR-13"],
    ),
}
