"""Manual BA use-case details — Listing & Search P0 (UC-LS-01 … UC-LS-07)."""
from __future__ import annotations

from wereal_ba_detail_helpers import uc_detail

LS_USE_CASE_DETAILS: dict[str, dict] = {
    "UC-LS-01": uc_detail(
        "UC-LS-01",
        "Tìm kiếm & lọc sản phẩm",
        screens="SCR-PUBLIC-005",
        actor="Buyer, Guest (P4 Thu Trang)",
        actor_secondary="System (OpenSearch, facet aggregator)",
        goal="Full-text + facet search P95 ≤200ms — chỉ PUBLISHED inventory",
        trigger="Guest landing search hoặc submit query/filter",
        pre="Search index synced UC-LS-07; public no auth",
        post="Results grid + facets; click → unit detail UC-LS-05",
        priority="P0 Must",
        trace="FR-LS-02, FR-LS-06 · BR-10, BR-20",
        api="GET /search/units · GET /search/suggest",
        prototype="/public/search · /uc/UC-LS-01",
        main=[
            [1, "SearchHero: query box + quick filters (quận, giá, loại căn)"],
            [2, "GET /search/units?q= — debounce 300ms · skeleton loading"],
            [3, "Facet sidebar: bedrooms, price bands, project, verified only"],
            [4, "Sort: price asc/desc, newest, absorption hot"],
            [5, "Result cards: thumbnail, verified badge BR-10, price, SSE status chip"],
            [6, "Compare checkbox (UC-LS-03) + pagination/infinite scroll"],
        ],
        alt=[
            ["E1", "Zero results → suggest relax filters + popular projects"],
            ["E2", "OpenSearch timeout → cached fallback + retry banner"],
        ],
        io_in="q, facets{}, sort, page, pageSize, geo?",
        io_out="hits[], facets{}, meta totalCount",
        rules=["BR-10", "BR-20", "BR-09"],
    ),
    "UC-LS-02": uc_detail(
        "UC-LS-02",
        "Duyệt listing trước publish",
        screens="SCR-ADMIN-016",
        actor="Ops Admin (P5 Quốc Bảo)",
        actor_secondary="System (OpenSearch indexer on approve)",
        goal="Chỉ listing đã duyệt + anti-drift pass mới vào search index public",
        trigger="Listing PENDING_REVIEW sau agent submit (UC-GR-02)",
        pre="Moderation queue populated; drift report available UC-GR-03",
        post="APPROVED → PUBLISHED index; REJECTED → agent notify",
        priority="P0 Must",
        trace="FR-LS-01 · BR-09, BR-10",
        api="PATCH /listings/{id}/approve|reject · POST publish-index job",
        prototype="/admin/moderation · /uc/UC-LS-02",
        main=[
            [1, "Ops filter queue tab «Publish review» — distinct from drift-only tab"],
            [2, "Preview listing content + media gallery quality check"],
            [3, "Verify anti-drift PASS from UC-GR-03 (block if FAIL)"],
            [4, "Approve → PATCH approve → outbox ListingPublished"],
            [5, "Worker index OpenSearch + invalidate CDN — lag ≤5s BR-20"],
            [6, "Public search UC-LS-01 reflects new listing; SSE unit if tied GR"],
        ],
        alt=[
            ["E1", "Reject → mandatory reason template → agent resubmit workflow"],
            ["E2", "Approve without drift pass → system block 422"],
        ],
        io_in="listingId, decision, publishNote, scheduledAt?",
        io_out="listing status PUBLISHED, index doc id, audit",
        rules=["BR-09", "BR-10", "BR-20"],
    ),
    "UC-LS-04": uc_detail(
        "UC-LS-04",
        "Upload media listing (ảnh/video)",
        screens="SCR-AGENT-010",
        actor="Agent (P3 Hoàng Nam)",
        actor_secondary="System (S3 presigned, virus scan worker)",
        goal="Media chất lượng, an toàn — gắn listing wizard UC-GR-02",
        trigger="Agent step media trong listing wizard hoặc edit listing",
        pre="Listing draft exists; cap listings.media.write",
        post="Media ATTACHED; scan CLEAN; gallery order saved",
        priority="P0 Must",
        trace="FR-LS-03",
        api="POST /media/presign · POST /media/{id}/attach · webhook scan result",
        prototype="/agent/listings/media · /uc/UC-LS-04",
        main=[
            [1, "Dropzone drag-drop — accept jpg/png/webp/mp4 limits FR-LS-03"],
            [2, "POST presign → direct upload S3 tenant prefix"],
            [3, "Progress bar per file; max 20 images + 1 video"],
            [4, "Virus scan async — QUARANTINE if fail, block publish"],
            [5, "Reorder gallery drag; set cover image"],
            [6, "Watermark optional tenant policy — preview before submit"],
        ],
        alt=[
            ["E1", "File >10MB → client reject before upload"],
            ["E2", "Scan INFECTED → delete object + toast agent"],
            ["E3", "Upload interrupt → resume multipart P2"],
        ],
        io_in="listingId, files[], coverIndex, altText[]",
        io_out="mediaIds[], scanStatus, gallery order",
        rules=["BR-09"],
    ),
    "UC-LS-05": uc_detail(
        "UC-LS-05",
        "Xem trang chi tiết project/unit",
        screens="SCR-PUBLIC-006",
        actor="Buyer, Guest",
        actor_secondary="System (SSE status UC-GR-07, lead form UC-CRM-01)",
        goal="Trust-first unit page — verified badge, giá minh bạch, lead ≤3 click",
        trigger="Click từ search/compare/deep link",
        pre="Unit/listing PUBLISHED in index",
        post="Page viewed analytics; optional lead submitted UC-CRM-01",
        priority="P0 Must",
        trace="FR-UX-01, FR-LS-02 · BR-10, BR-15",
        api="GET /listings/{id} · GET /units/{id} public view · SSE subscribe",
        prototype="/public/units/un_01 · /uc/UC-LS-05",
        main=[
            [1, "Gallery carousel + lightbox — cover from listing media"],
            [2, "Spec panel: diện tích, pháp lý, hướng — synced GR read-only"],
            [3, "Verified badge + «Giá từ Developer» tooltip BR-10"],
            [4, "Live status chip SSE: AVAILABLE / RESERVED countdown"],
            [5, "Sticky LeadForm UC-CRM-01 — mobile bottom sheet"],
            [6, "Related units + CTA compare UC-LS-03"],
        ],
        alt=[
            ["E1", "Unit RESERVED → CTA đổi «Đăng ký chờ» waitlist P2"],
            ["E2", "Listing unpublished mid-session → 410 + search redirect"],
        ],
        io_in="unitId or listingId slug, utm params",
        io_out="page view event, optional leadId",
        rules=["BR-10", "BR-15", "BR-20"],
    ),
    "UC-LS-07": uc_detail(
        "UC-LS-07",
        "Đồng bộ search index từ Golden Record",
        screens="SCR-SYS-003",
        actor="System (CDC outbox worker)",
        actor_secondary="OpenSearch cluster, cache invalidation",
        goal="Search index reflects GR/listing changes ≤5s lag BR-20",
        trigger="Domain events UnitUpdated, ListingPublished, ListingUnpublished",
        pre="Outbox table populated; OpenSearch index template per tenant",
        post="Index doc upsert/delete; CDN purge; monitor lag metric",
        priority="P0 Must",
        trace="FR-LS-06 · BR-20",
        api="Internal outbox consumer · OpenSearch bulk API · CDN purge hook",
        prototype="System — /uc/UC-LS-07",
        main=[
            [1, "GR/Listing service write → outbox row transactional"],
            [2, "Worker poll outbox — map entity → search document schema"],
            [3, "Bulk upsert OpenSearch — tenant alias routing"],
            [4, "Delete doc on UNPUBLISH or SOLD hide policy"],
            [5, "Emit lag metric; alert if p95 >5s"],
            [6, "Public search UC-LS-01 eventual consistency verified E2E"],
        ],
        alt=[
            ["E1", "OpenSearch bulk fail → retry exponential + DLQ"],
            ["E2", "Schema migration → reindex job coordinated"],
        ],
        io_in="outbox events: entityType, entityId, operation, payload",
        io_out="indexed doc id, lagMs, purge tags",
        rules=["BR-20", "BR-09"],
    ),
}
