"""Deep SCR UI/API overrides — Commission COM & Trust TR."""
from __future__ import annotations

from wereal_ba_detail_helpers import scr_detail

P0_COM_TR_SCREEN_DETAILS: dict[str, dict] = {
    "SCR-DEV-004": scr_detail(
        "SCR-DEV-004",
        "Commission Policy Editor",
        route="/developer/commission",
        module="MOD-COM — Commission",
        purpose="Developer cấu hình tỷ lệ HH theo project — versioned publish workflow",
        roles="Developer Admin",
        linked_ucs="UC-COM-01",
        app="Portal Chủ đầu tư (Developer)",
        trace="FR-COM-01",
        api="GET/POST/PATCH /commission/policies · POST /policies/{id}/publish",
        pre="cap com.policy.manage; project scope ABAC",
        post="Policy DRAFT saved or PUBLISHED with new version",
        notes="Accent gold KPI highlights · policy diff sidebar",
        ui=[
            [1, "ProjectPolicySelector", "Select", "Có", "Dropdown project + active version badge"],
            [2, "PolicyVersionTimeline", "Timeline", "Có", "Historical versions read-only"],
            [3, "BaseRateForm", "Form", "Có", "Percent input tabular-nums validation"],
            [4, "TierRulesTable", "EditableTable", "Không", "Volume tiers P2 optional"],
            [5, "SplitRulesBuilder", "Form", "Có", "Agent/agency/platform split — sum 100% meter"],
            [6, "EffectiveDatePicker", "Date", "Có", "From date + optional sunset"],
            [7, "HoldbackDefaultField", "Input", "Có", "Default % link dispute UC-COM-04"],
            [8, "SimulationPreview", "Panel", "Không", "Sample deal commission read-only"],
            [9, "PublishPolicyButton", "Button", "Có", "Confirm modal BR-13 non-retroactive"],
        ],
        rules=["BR-13", "BR-19", "BR-08"],
    ),
    "SCR-SYS-001": scr_detail(
        "SCR-SYS-001",
        "Commission Snapshot Worker (system)",
        route="/uc/UC-COM-02",
        module="MOD-COM — System",
        purpose="Persist immutable policy snapshot on deal complete — no primary UI",
        roles="System, Finance (read-only API)",
        linked_ucs="UC-COM-02",
        app="NestJS consumer + append-only snapshot store",
        trace="FR-COM-02",
        api="Internal snapshot service · GET /deals/{id}/commission-snapshot",
        status_note="Draft — backend component",
        ui=[
            [1, "SnapshotHealthPanel", "Monitor", "Có", "Lag queue, failed snapshots count"],
            [2, "RecentSnapshotsLog", "Log", "Có", "dealId, policyVersion, hash, createdAt"],
            [3, "ReplayDlqButton", "Action", "Có", "DevOps retry failed events only"],
        ],
        rules=["BR-13", "BR-24", "BR-08"],
    ),
    "SCR-FIN-002": scr_detail(
        "SCR-FIN-002",
        "Commission Split Review",
        route="/finance/commission/split",
        module="MOD-COM — Finance",
        purpose="Finance duyệt phân bổ HH từ snapshot — settlement queue",
        roles="Finance Admin",
        linked_ucs="UC-COM-03",
        app="Finance Portal",
        trace="FR-COM-03",
        api="GET /finance/commission/splits · POST /commission/lines/approve",
        ui=[
            [1, "SplitQueueFilters", "Filter", "Có", "Period, project, agency, status"],
            [2, "SplitReviewTable", "DataTable", "Có", "Deal ref, snapshot ver, gross, status chip"],
            [3, "LineBreakdownDrawer", "Drawer", "Có", "Per agent/agency lines + KYC status"],
            [4, "RoundingAdjustmentForm", "Form", "Không", "±1 VND with dual approval"],
            [5, "HoldbackIndicator", "Badge", "Có", "Link dispute UC-TR-03 if HELD"],
            [6, "ApproveBatchToolbar", "Toolbar", "Có", "Multi-select → settlement run"],
        ],
        rules=["BR-13", "BR-23", "BR-08"],
    ),
    "SCR-ADMIN-007": scr_detail(
        "SCR-ADMIN-007",
        "Commission Holdback Console",
        route="/admin/commission/holdback",
        module="MOD-COM + MOD-TR",
        purpose="Ops giữ HH khi tranh chấp — release khi resolved",
        roles="Ops Admin, Legal override",
        linked_ucs="UC-COM-04, UC-TR-03",
        app="Admin / Ops Portal",
        trace="FR-COM-04, FR-TR-03",
        api="POST /commission/holdback · POST /holdback/{id}/release",
        ui=[
            [1, "OpenDisputesPanel", "List", "Có", "Disputes OPEN linked bookings"],
            [2, "HoldbackForm", "Form", "Có", "Lines select, percent, reason code"],
            [3, "HeldLinesTable", "Table", "Có", "Amount held, agent, dispute ref"],
            [4, "ReleaseWorkflow", "Stepper", "Có", "Partial/full release + notes"],
            [5, "AuditLink", "Link", "Có", "Jump UC-TR-01 filtered holdback events"],
        ],
        rules=["BR-08", "BR-13", "BR-24"],
    ),
    "SCR-FIN-001": scr_detail(
        "SCR-FIN-001",
        "Commission Export",
        route="/finance/commission/export",
        module="MOD-COM — Finance",
        purpose="Export báo cáo HH kế toán XLSX/CSV với audit checksum",
        roles="Finance Admin",
        linked_ucs="UC-COM-05",
        app="Finance Portal",
        trace="FR-COM-05",
        api="POST /finance/commission/export",
        ui=[
            [1, "ExportPeriodPicker", "DateRange", "Có", "From/to + preset month"],
            [2, "ProjectMultiSelect", "Select", "Có", "Filter tenant projects"],
            [3, "FormatToggle", "Radio", "Có", "XLSX | CSV"],
            [4, "IncludeHoldbackSheet", "Checkbox", "Có", "Separate tab held lines"],
            [5, "PreviewColumnList", "List", "Có", "dealId, snapshotHash, amounts…"],
            [6, "GenerateExportButton", "Button", "Có", "Async job progress bar"],
            [7, "DownloadHistoryTable", "Table", "Có", "Past exports + checksum"],
        ],
        rules=["BR-08", "BR-04", "BR-13"],
    ),
    "SCR-ADMIN-005": scr_detail(
        "SCR-ADMIN-005",
        "Audit Trail Explorer",
        route="/admin/audit",
        module="MOD-TR — Trust & Compliance",
        purpose="Platform/tenant audit search — immutable event store UI",
        roles="Ops Admin, Platform Admin, Legal read-only",
        linked_ucs="UC-TR-01, UC-BK-03",
        app="Admin / Ops Portal",
        trace="FR-TR-01",
        api="GET /audit/events · POST /audit/export",
        pre="cap audit.read; MFA recommended platform scope",
        post="Filtered events displayed; export job queued if large",
        ui=[
            [1, "AuditFilterBar", "Filter", "Có", "Entity, actor, date, tenant, correlationId"],
            [2, "EventStreamTable", "DataTable", "Có", "Sort desc timestamp; virtual scroll"],
            [3, "EventDetailDrawer", "Drawer", "Có", "JSON diff before/after + metadata"],
            [4, "CorrelationChainView", "Timeline", "Có", "Grouped events same request chain"],
            [5, "ExportAuditButton", "Button", "Có", "CSV/JSON scoped export BR-24"],
            [6, "PiiMaskToggle", "Toggle", "Có", "Legal role unmask with reason"],
        ],
        rules=["BR-08", "BR-24"],
    ),
    "SCR-DEV-006": scr_detail(
        "SCR-DEV-006",
        "Document Vault",
        route="/developer/documents",
        module="MOD-TR — Trust & Compliance",
        purpose="Developer quản lý tài liệu pháp lý — watermark download",
        roles="Developer Admin",
        linked_ucs="UC-TR-02",
        app="Portal Chủ đầu tư (Developer)",
        trace="FR-TR-02",
        api="POST /documents/presign · GET /documents/{id}/download",
        ui=[
            [1, "FolderTree", "Tree", "Có", "Project / Legal / Marketing folders"],
            [2, "DocumentUploadZone", "Upload", "Có", "Presigned multi-file + scan status"],
            [3, "MetadataForm", "Form", "Có", "docType, retention, unit link optional"],
            [4, "DocumentListTable", "Table", "Có", "Name, version, scan, updated"],
            [5, "AccessLogTab", "Table", "Có", "Download audit per document"],
            [6, "ShareLinkModal", "Modal", "Không", "Internal expiring links"],
        ],
        rules=["BR-08", "BR-24", "BR-09"],
    ),
    "SCR-ADMIN-008": scr_detail(
        "SCR-ADMIN-008",
        "Dispute Center",
        route="/admin/disputes",
        module="MOD-TR — Trust & Compliance",
        purpose="Quản lý tranh chấp end-to-end — SLA timer, evidence pack",
        roles="Ops Admin, Legal",
        linked_ucs="UC-TR-03, UC-COM-04",
        app="Admin / Ops Portal",
        trace="FR-TR-03",
        api="POST /disputes · POST /disputes/{id}/resolve",
        ui=[
            [1, "DisputeQueueTable", "DataTable", "Có", "SLA countdown chip red <6h"],
            [2, "CreateDisputeModal", "Modal", "Có", "Booking link, category, attachments"],
            [3, "EvidenceAutoAttachPanel", "Panel", "Có", "Timeline, ledger, drift check preview"],
            [4, "MediationThread", "Chat", "Có", "Internal notes + templated outbound"],
            [5, "ResolutionForm", "Form", "Có", "Outcome enum + link refund/holdback actions"],
            [6, "EvidencePackDownload", "Button", "Có", "PDF bundle on close"],
        ],
        rules=["BR-08", "BR-24", "BR-02", "BR-22"],
    ),
    "SCR-ADMIN-018": scr_detail(
        "SCR-ADMIN-018",
        "Regulatory Export Wizard",
        route="/admin/regulatory-export",
        module="MOD-TR — Trust & Compliance",
        purpose="Enterprise compliance pack — encrypted multi-tenant export",
        roles="Platform Admin, Legal approver",
        linked_ucs="UC-TR-04",
        app="Admin Portal",
        trace="FR-TR-04",
        api="POST /regulatory-export/jobs",
        status_note="Pending — Phase 4 enterprise",
        ui=[
            [1, "ExportScopeWizard", "Stepper", "Có", "Tenant, date, pack type selection"],
            [2, "LegalApprovalStep", "Form", "Có", "Ticket ID + MFA OTP BR-14"],
            [3, "RedactionRulesPreview", "Panel", "Có", "PII fields masked list"],
            [4, "JobProgressMonitor", "Progress", "Có", "Compile + encrypt stages"],
            [5, "ManifestChecksumDisplay", "Text", "Có", "SHA-256 manifest download"],
            [6, "OneTimeDownloadLink", "Alert", "Có", "72h expiry warning"],
        ],
        rules=["BR-08", "BR-24", "BR-14"],
    ),
}
