"""Manual BA use-case details — Trust & Compliance TR (UC-TR-01 … UC-TR-04)."""
from __future__ import annotations

from wereal_ba_detail_helpers import uc_detail

TR_USE_CASE_DETAILS: dict[str, dict] = {
    "UC-TR-01": uc_detail(
        "UC-TR-01",
        "Xem audit trail toàn hệ thống",
        screens="SCR-ADMIN-005",
        actor="Ops Admin (P5 Quốc Bảo)",
        actor_secondary="Platform Admin, Legal (read-only export)",
        goal="Immutable audit cho mọi mutation — dispute & regulatory evidence BR-08, BR-24",
        trigger="Ops điều tra incident, tranh chấp, hoặc scheduled compliance review",
        pre="cap audit.read; tenant context Platform or scoped tenant; MFA admin optional NFR-S05",
        post="Filtered event list; detail drawer; export pack fragment if scoped",
        priority="P0 Must",
        phase="Phase 1",
        trace="FR-TR-01 · BR-08, BR-24",
        api="GET /audit/events · GET /audit/events/{id} · POST /audit/export",
        prototype="/admin/audit · /uc/UC-TR-01",
        main=[
            [1, "Ops mở Audit Explorer — default last 24h platform-wide or tenant filter"],
            [2, "Filter: entityType (unit|booking|payment|listing|user), entityId, actor, date range"],
            [3, "Event table: timestamp, actor, action, entity, tenantId, correlationId"],
            [4, "Click row → drawer JSON diff before/after + IP + userAgent + requestId"],
            [5, "Chain view: correlationId groups related events (booking→pay→ledger)"],
            [6, "Export CSV/JSON filtered set — append-only store guarantee no delete UI"],
        ],
        alt=[
            ["E1", "Cross-tenant query without platform role → 403"],
            ["E2", "Export >100k rows → async job + signed URL 24h"],
            ["E3", "PII mask in export unless Legal role + reason logged"],
        ],
        io_in="filters{entityType, entityId, actorId, from, to}, exportFormat",
        io_out="events[], exportJobId?, downloadUrl?",
        rules=["BR-08", "BR-24"],
    ),
    "UC-TR-02": uc_detail(
        "UC-TR-02",
        "Quản lý kho tài liệu (Document Vault)",
        screens="SCR-DEV-006",
        actor="Developer Admin",
        actor_secondary="Ops Admin (moderation access P2), Buyer (expiring view link P3)",
        goal="Lưu trữ pháp lý project/unit — watermark + access log BR-08",
        trigger="Developer upload hợp đồng mẫu, pháp lý project, hoặc Ops request evidence",
        pre="cap documents.manage; virus scan pipeline; storage quota per tenant",
        post="Document STORED; metadata indexed; download requires authorized role",
        priority="P1 Should",
        phase="Phase 2",
        trace="FR-TR-02 · BR-08, BR-09",
        api="POST /documents/presign · POST /documents · GET /documents/{id}/download",
        prototype="/developer/documents · /uc/UC-TR-02",
        main=[
            [1, "Developer mở Document Vault — folder tree Project / Legal / Marketing"],
            [2, "Upload presigned S3 — PDF/DOCX max size; async virus scan"],
            [3, "Tag: docType, projectId, unitId optional, retention class 5y BR-24"],
            [4, "Enable watermark on download: tenant + user + timestamp overlay"],
            [5, "Share internal link — role-scoped expiry 7d default"],
            [6, "Access log tab: who downloaded when — export for audit UC-TR-01"],
        ],
        alt=[
            ["E1", "Scan QUARANTINE → block download + notify Security"],
            ["E2", "Delete soft-only — tombstone retained for legal retention"],
        ],
        io_in="file, metadata{docType, projectId, retentionClass}, watermark=true",
        io_out="documentId, scanStatus, accessLogUrl",
        rules=["BR-08", "BR-24", "BR-09"],
    ),
    "UC-TR-03": uc_detail(
        "UC-TR-03",
        "Quản lý tranh chấp (Dispute Center)",
        screens="SCR-ADMIN-008",
        actor="Ops Admin",
        actor_secondary="Legal, Finance (holdback UC-COM-04), Agent/Buyer (submit evidence)",
        goal="Giải quyết tranh chấp giá/giữ chỗ/HH — SLA <48h Phase 3 OP-WIN-10",
        trigger="Buyer/Agent mở dispute hoặc Ops escalate từ booking timeline UC-BK-03",
        pre="cap disputes.manage; booking/deal exists; event timeline available BR-24",
        post="Dispute RESOLVED|ESCALATED; evidence pack archived; commission holdback updated",
        priority="P1 Must",
        phase="Phase 2–3",
        trace="FR-TR-03 · BR-08, BR-02, BR-24",
        api="POST /disputes · GET /disputes/{id} · POST /disputes/{id}/resolve",
        prototype="/admin/disputes · /uc/UC-TR-03",
        main=[
            [1, "Ops mở Dispute Queue — sort SLA breach ascending"],
            [2, "Create dispute: link bookingId, category, description, attachments"],
            [3, "Auto-attach evidence: booking timeline UC-BK-03, payment ledger, listing drift check"],
            [4, "Mediation workflow: messages internal + templated buyer/agent notifications"],
            [5, "Decision: refund partial | release booking | commission adjust → link UC-PAY-03 / UC-COM-04"],
            [6, "Close RESOLVED — generate evidence PDF pack; audit DISPUTE_CLOSED"],
        ],
        alt=[
            ["E1", "SLA 48h breach → escalate Platform Admin + steering alert"],
            ["E2", "Duplicate dispute same booking → merge threads"],
            ["E3", "Legal hold → block auto-release commission until Legal sign-off"],
        ],
        io_in="bookingId, category, description, attachments[], resolution{outcome, notes}",
        io_out="disputeId, status, evidencePackUrl, holdbackId?",
        rules=["BR-08", "BR-24", "BR-02", "BR-22"],
    ),
    "UC-TR-04": uc_detail(
        "UC-TR-04",
        "Regulatory Export Pack",
        screens="SCR-ADMIN-018",
        actor="Platform Admin",
        actor_secondary="Legal, External auditor (one-time token)",
        goal="Xuất gói tuân thủ: audit + transactions + policies — encrypted BR-24",
        trigger="Regulatory request, annual audit, hoặc enterprise contract SLA G4.5",
        pre="cap regulatory.export; Legal approval ticket; scope tenant/date defined",
        post="Encrypted ZIP + manifest checksum; download logged; retention notice",
        priority="P2 Could",
        phase="Phase 4",
        trace="FR-TR-04 · BR-08, BR-24",
        api="POST /regulatory-export/jobs · GET /regulatory-export/{id}",
        prototype="/admin/regulatory-export · /uc/UC-TR-04",
        main=[
            [1, "Platform Admin mở Regulatory Export — wizard scope tenant(s), date range"],
            [2, "Select packs: AuditEvents, Bookings, Payments/Ledger, CommissionSnapshots, Policies"],
            [3, "Legal approver MFA confirm + ticket reference number"],
            [4, "Background job compile — PII redaction rules per jurisdiction template"],
            [5, "Encrypt AES-256 password via separate channel; manifest SHA-256 all files"],
            [6, "Auditor download once — link expires 72h; full audit REG_EXPORT_COMPLETED"],
        ],
        alt=[
            ["E1", "Scope too large → split multi-part export"],
            ["E2", "Missing events gap detected → block export + incident UC-TR-01"],
        ],
        io_in="tenantIds[], from, to, packTypes[], legalTicketId, mfaOtp",
        io_out="exportJobId, manifestHash, encryptedDownloadUrl",
        rules=["BR-08", "BR-24", "BR-14"],
    ),
}
