"""Manual BA use-case details — Booking P0 (UC-BK-01 … UC-BK-05)."""
from __future__ import annotations

from wereal_ba_detail_helpers import uc_detail

BK_USE_CASE_DETAILS: dict[str, dict] = {
    "UC-BK-01": uc_detail(
        "UC-BK-01",
        "Tạo booking/giữ chỗ với expiry",
        screens="SCR-AGENT-005",
        actor="Agent (P3 Hoàng Nam)",
        actor_secondary="System (Redis atomic lock, expiry scheduler)",
        goal="Giữ chỗ unit atomic — zero double booking; expiry 48h default",
        trigger="Agent chốt khách gallery chọn unit + lead",
        pre="Unit AVAILABLE; lead qualified; cap bookings.create; Idempotency-Key header",
        post="Booking RESERVED; unit lock; expiresAt set; notification buyer/agent",
        priority="P0 Must",
        trace="FR-BK-01, FR-BK-02 · BR-02, BR-03, BR-17",
        api="POST /api/v1/bookings (Idempotency) · Redis lock · POST transitions",
        prototype="/agent/bookings/new · /uc/UC-BK-01",
        main=[
            [1, "Agent chọn lead (pipeline) + unit GR/search — realtime status SSE UC-GR-07"],
            [2, "Form: depositAmount, expiryHours (default 48 OI-08), notes"],
            [3, "POST /bookings với Idempotency-Key — server acquire Redis lock FR-BK-02"],
            [4, "Success 201 → status RESERVED; unit → RESERVED; countdown timer UI"],
            [5, "Scheduler job enqueue expiry at expiresAt BR-17"],
            [6, "One-click payment link gửi buyer (handoff UC-PAY-01) — BR-02"],
        ],
        alt=[
            ["E1", "409 Conflict — unit vừa bị book → show who/when; suggest alternate unit"],
            ["E2", "Duplicate Idempotency-Key → return same booking 200/201"],
            ["E3", "Expiry reached → auto RELEASE lock; unit AVAILABLE; notify BR-17"],
        ],
        io_in="unitId, leadId, depositAmount, expiryHours, idempotencyKey, notes",
        io_out="bookingId, lockId, expiresAt, status RESERVED, domain events",
        rules=["BR-02", "BR-03", "BR-17", "BR-08"],
    ),
    "UC-BK-02": uc_detail(
        "UC-BK-02",
        "Theo dõi trạng thái giao dịch",
        screens="SCR-BUYER-002",
        actor="Buyer (P4 Thu Trang)",
        actor_secondary="Agent (read-only extended view)",
        goal="Buyer và agent theo dõi 15-state deal stepper minh bạch",
        trigger="Buyer login hoặc magic link từ SMS/email sau booking",
        pre="Booking linked to buyer identity; auth buyer portal",
        post="Stepper reflects current state; allowed actions visible per role",
        priority="P0 Must",
        trace="FR-BK-03 · BR-02",
        api="GET /bookings/{id} · GET allowedTransitions · BFF /buyer/deals",
        prototype="/buyer/deals · /uc/UC-BK-02",
        main=[
            [1, "Buyer mở DealTracker — list bookings active"],
            [2, "15-state stepper: RESERVED → DEPOSIT_PENDING → DEPOSITED → … → CLOSED"],
            [3, "Mỗi state: timestamp, actor, short description tiếng Việt"],
            [4, "CTA theo state: Pay deposit (UC-PAY-01), Upload doc, View contract P2"],
            [5, "Push/ZNS notify on transition (P2 NW-01)"],
            [6, "Agent view thêm internal notes tab — buyer không thấy"],
        ],
        alt=[
            ["E1", "Expired RESERVED → stepper shows EXPIRED + CTA contact agent"],
            ["E2", "Buyer limited fields vs agent — ABAC field mask"],
        ],
        io_in="bookingId, buyerSession",
        io_out="booking state, stepper steps[], allowedActions[]",
        rules=["BR-02", "BR-08"],
    ),
    "UC-BK-03": uc_detail(
        "UC-BK-03",
        "Xem domain event timeline giao dịch",
        screens="SCR-AGENT-003",
        actor="Agent, Ops Admin",
        actor_secondary="System (event store append-only)",
        goal="Timeline human-readable mọi transition booking cho ops và dispute",
        trigger="Agent/Ops mở booking detail timeline tab",
        pre="cap bookings.read; event store populated FR-BK-04",
        post="Timeline ordered; exportable for dispute UC-BK-04 P2",
        priority="P0 Must",
        trace="FR-BK-04 · BR-08, BR-24",
        api="GET /bookings/{id}/timeline · GET /bookings/{id}/events",
        prototype="/agent/bookings/bk_018 · /uc/UC-BK-03",
        main=[
            [1, "Open booking detail — tab Timeline (default for Ops)"],
            [2, "GET /timeline — aggregate domain events + human labels"],
            [3, "Each entry: icon, actor, timestamp, payload summary, correlationId"],
            [4, "Filter: state changes | payment | moderation | system"],
            [5, "Link to related payment ledger entries UC-PAY-02"],
            [6, "Retention ≥5y — read-only archive BR-24"],
        ],
        alt=[
            ["E1", "Missing event (gap) → incident flag + replay from store P2 UC-BK-04"],
            ["E2", "Ops export CSV/PDF evidence pack"],
        ],
        io_in="bookingId, filter, dateRange",
        io_out="timeline events[], metadata totalCount",
        rules=["BR-08", "BR-24"],
    ),
    "UC-BK-05": uc_detail(
        "UC-BK-05",
        "Hủy booking & hoàn tiền",
        screens="SCR-AGENT-004",
        actor="Agent",
        actor_secondary="Finance Admin (refund approval), System (ledger)",
        goal="Cancel chain: release lock → refund → ledger reversal → unit available",
        trigger="Agent hoặc buyer request cancel trước/sau deposit",
        pre="Booking in cancellable state; cancel reason required",
        post="Booking CANCELLED/REFUNDED; unit AVAILABLE; ledger balanced BR-22",
        priority="P0 Must",
        trace="FR-BK-07 · BR-22",
        api="DELETE /bookings/{id} · POST /refunds · POST transitions CANCEL",
        prototype="/agent/bookings/cancel · /uc/UC-BK-05",
        main=[
            [1, "Agent mở CancelBooking — summary deposit paid amount"],
            [2, "Chọn cancel reason (enum) + optional note — MFA if deposit paid BR-14"],
            [3, "POST transition CANCEL — release Redis unit lock"],
            [4, "If deposit SUCCEEDED → trigger UC-PAY-03 refund workflow"],
            [5, "Booking status REFUNDED; unit AVAILABLE via SSE UC-GR-07"],
            [6, "Timeline event Cancelled + RefundInitiated appended UC-BK-03"],
        ],
        alt=[
            ["E1", "Non-cancellable state (CONTRACT_SIGNED) → 422 + suggest dispute UC-TR-03"],
            ["E2", "Partial refund policy — Finance override"],
            ["E3", "Refund gateway fail → booking REFUND_PENDING + retry job"],
        ],
        io_in="bookingId, cancelReason, refundAmount?, mfaOtp?",
        io_out="booking status, refundId, ledger reversal entries, unit status",
        rules=["BR-22", "BR-03", "BR-14", "BR-18"],
    ),
}
