"""Manual BA use-case details — Payment P0 (UC-PAY-01 … UC-PAY-03)."""
from __future__ import annotations

from wereal_ba_detail_helpers import uc_detail

PAY_USE_CASE_DETAILS: dict[str, dict] = {
    "UC-PAY-01": uc_detail(
        "UC-PAY-01",
        "Tạo & thanh toán cọc online",
        screens="SCR-BUYER-004",
        actor="Buyer (P4 Thu Trang)",
        actor_secondary="System (VNPay adapter, webhook, ledger)",
        goal="Thanh toán cọc online qua platform — GMV north star BR-11",
        trigger="Buyer click Pay từ DealTracker hoặc payment link agent",
        pre="Booking DEPOSIT_PENDING; payment intent created; gateway configured CON-03",
        post="Payment SUCCEEDED; booking DEPOSITED; double-entry ledger BR-18; receipt",
        priority="P0 Must",
        trace="FR-PAY-01, FR-PAY-02, FR-PAY-05 · BR-02, BR-14, BR-21",
        api="POST /payment-intents · POST /webhooks/payment · MFA OTP",
        prototype="/buyer/payment · /uc/UC-PAY-01",
        main=[
            [1, "Buyer mở PaymentPage — amount, booking ref, expiry countdown"],
            [2, "POST /payment-intents {bookingId, amount} → pi_01 + VNPay URL/QR"],
            [3, "Buyer MFA OTP confirm before redirect BR-14 NFR-S05"],
            [4, "Redirect VNPay / scan QR — buyer completes on gateway"],
            [5, "Webhook POST /webhooks/payment — HMAC verify, idempotent eventId BR-21"],
            [6, "Ledger debit/credit + booking transition DEPOSITED + receipt URL"],
        ],
        alt=[
            ["E1", "Duplicate webhook eventId → 200 processed:false skip ledger"],
            ["E2", "Payment timeout → intent EXPIRED; booking stays DEPOSIT_PENDING"],
            ["E3", "Amount mismatch webhook vs intent → quarantine + Finance alert"],
            ["E4", "MFA fail → block redirect; 3 attempts lock 15min"],
        ],
        io_in="bookingId, amount, paymentMethod, mfaOtp, idempotencyKey",
        io_out="paymentIntentId, gatewayRef, ledgerEntryIds[], booking status DEPOSITED",
        rules=["BR-02", "BR-11", "BR-14", "BR-18", "BR-21"],
    ),
    "UC-PAY-02": uc_detail(
        "UC-PAY-02",
        "Đối soát thanh toán hàng ngày",
        screens="SCR-FIN-004",
        actor="Finance Admin (P6 Kim Anh)",
        actor_secondary="System (reconciliation batch job 02:00 ICT)",
        goal="Đối soát gateway vs ledger 100% — không Excel BR-04",
        trigger="Scheduled daily reconcile hoặc Finance mở dashboard sáng",
        pre="cap finance.reconcile; gateway settlement file/API available",
        post="Reconcile report MATCH hoặc discrepancy list assigned",
        priority="P0 Must",
        trace="FR-PAY-04 · BR-04, BR-11, BR-18",
        api="GET /finance/reconciliation?date= · POST /reconciliation/run",
        prototype="/finance/reconciliation · /uc/UC-PAY-02",
        main=[
            [1, "Finance mở ReconciliationDashboard — chọn business date D"],
            [2, "Batch job aggregate: sum gateway settlements vs ledger credits"],
            [3, "Match table: txnId, gatewayRef, ledgerId, amount, status"],
            [4, "100% match → green badge + auto-close day"],
            [5, "Discrepancy → red rows: MISSING_GATEWAY | MISSING_LEDGER | AMOUNT_MISMATCH"],
            [6, "Export CSV + assign owner; block period close until resolved"],
        ],
        alt=[
            ["E1", "Gateway API down → retry 3x; alert DevOps"],
            ["E2", "Manual adjustment entry — dual approval + audit"],
        ],
        io_in="businessDate, gatewayId, filters",
        io_out="reconciliationRunId, matchRate, discrepancies[]",
        rules=["BR-04", "BR-11", "BR-18", "BR-21"],
    ),
    "UC-PAY-03": uc_detail(
        "UC-PAY-03",
        "Xử lý refund & ledger reversal",
        screens="SCR-FIN-005",
        actor="Finance Admin",
        actor_secondary="System (gateway refund API, booking sync)",
        goal="Refund idempotent với ledger reversal cân bằng — liên kết cancel BR-22",
        trigger="Cancel booking UC-BK-05 hoặc Finance manual refund request",
        pre="Payment SUCCEEDED; refund policy allows; MFA Finance BR-14",
        post="Refund SUCCEEDED/PROCESSING; ledger reversed; booking REFUNDED",
        priority="P0 Must",
        trace="FR-PAY-02 · BR-18, BR-22, BR-21",
        api="POST /refunds · POST gateway/refund · PATCH booking",
        prototype="/finance/refunds · /uc/UC-PAY-03",
        main=[
            [1, "Refund queue — filter PENDING from booking cancels"],
            [2, "Finance review: amount, reason, original payment ref"],
            [3, "MFA confirm → POST /refunds {paymentId, amount, reason}"],
            [4, "Gateway refund API — track provider refundId"],
            [5, "Ledger reversal entries (mirror original) BR-18 double-entry"],
            [6, "Webhook refund.success → close refund; notify buyer/agent"],
        ],
        alt=[
            ["E1", "Partial refund — split ledger lines"],
            ["E2", "Gateway refund fail → status FAILED + manual wire workflow"],
            ["E3", "Duplicate refund request → idempotency return existing"],
        ],
        io_in="paymentId, refundAmount, reason, bookingId, mfaOtp",
        io_out="refundId, ledgerReversalIds[], booking status REFUNDED",
        rules=["BR-18", "BR-22", "BR-21", "BR-14"],
    ),
}
