"""Manual BA use-case details — Golden Record P0 (UC-GR-01 … UC-GR-07)."""
from __future__ import annotations

from wereal_ba_detail_helpers import uc_detail

GR_USE_CASE_DETAILS: dict[str, dict] = {
    "UC-GR-01": uc_detail(
        "UC-GR-01",
        "Quản lý Golden Record (Unit gốc)",
        screens="SCR-DEV-012",
        actor="Developer Admin (P1 Minh Tuấn)",
        actor_secondary="System (versioning worker, audit)",
        goal="Developer là nguồn sự thật duy nhất về giá, diện tích, trạng thái tồn kho unit",
        trigger="Developer mở bảng hàng project hoặc cập nhật sau điều chỉnh giá/tồn",
        pre="Tenant Developer active; user có cap gr.units.write; project đã onboard",
        post="Unit GR version mới; audit trail immutable; Agency chỉ read giá gốc (CON-09)",
        priority="P0 Must",
        trace="FR-GR-01, FR-GR-02 · BR-01",
        api="GET/PATCH /api/v1/units · GET /units/{id}/versions · POST audit",
        prototype="/developer/units · /uc/UC-GR-01",
        main=[
            [1, "Developer Admin chọn project từ ProjectSelector (ABAC project scope)"],
            [2, "UnitGrid load GET /units?projectId= — filter tower/floor/status"],
            [3, "Inline edit giá/list price hoặc status AVAILABLE→HOLD (optimistic lock version)"],
            [4, "PATCH /units/{id} với expectedVersion — tạo version snapshot FR-GR-02"],
            [5, "AuditDrawer hiển thị actor, old/new value, timestamp — BR-08"],
            [6, "Outbox event UnitPriceChanged → search sync worker (UC-LS-07, BR-20)"],
        ],
        alt=[
            ["E1", "Agency user cố PATCH giá gốc → 403 Forbidden (BR-01, CON-09)"],
            ["E2", "Version conflict (409) → UI reload grid + hiển thị diff"],
            ["E3", "Unit đang RESERVED/BOOKED → chặn chuyển AVAILABLE trực tiếp"],
        ],
        io_in="projectId, unitId, price, listPrice, status, area, expectedVersion",
        io_out="unit record + versionId + domain event + audit log",
        rules=["BR-01", "BR-08", "BR-20"],
    ),
    "UC-GR-02": uc_detail(
        "UC-GR-02",
        "Tạo listing marketing từ unit gốc",
        screens="SCR-AGENT-011",
        actor="Agent (P3 Hoàng Nam)",
        actor_secondary="System (anti-drift engine)",
        goal="Listing marketing bám GR — không drift giá/diện tích so với unit gốc",
        trigger="Agent chọn unit GR available và bắt đầu wizard listing",
        pre="Unit status AVAILABLE hoặc DISTRIBUTABLE; Agency có quyền bán project (P2 MKT); GR readable",
        post="Listing draft PENDING_REVIEW; anti-drift score pass; chưa public",
        priority="P0 Must",
        trace="FR-GR-03, FR-GR-04 · BR-01, BR-06",
        api="POST /api/v1/listings · GET /units/{id} · POST /listings/{id}/drift-check",
        prototype="/agent/listings/new · /uc/UC-GR-02",
        main=[
            [1, "Agent search unit GR theo project — chỉ hiện unit eligible distribution"],
            [2, "Step 1: chọn unit → snapshot GR fields read-only (giá, diện tích, pháp lý)"],
            [3, "Step 2: nhập marketing copy + media (UC-LS-04); optional AI copilot UC-AI-01"],
            [4, "Anti-drift check: so sánh listing vs GR — flag nếu lệch > threshold FR-GR-04"],
            [5, "Agent xác nhận disclaimer AI (BR-16) nếu dùng copilot"],
            [6, "Submit → status PENDING_REVIEW → queue SCR-ADMIN-016"],
        ],
        alt=[
            ["E1", "Drift BLOCK → không submit; highlight field lệch vs GR"],
            ["E2", "AI copy auto-publish bị chặn — bắt buộc human approve BR-06"],
            ["E3", "Unit locked bởi booking RESERVED → 422 unavailable"],
        ],
        io_in="unitId, marketingTitle, description, mediaIds[], priceDisplay (optional override with cap)",
        io_out="listingId, driftReport, status PENDING_REVIEW",
        rules=["BR-01", "BR-06", "BR-09", "BR-16"],
    ),
    "UC-GR-03": uc_detail(
        "UC-GR-03",
        "Kiểm tra anti-drift listing",
        screens="SCR-ADMIN-016",
        actor="Ops Admin (P5 Quốc Bảo)",
        actor_secondary="System (drift scanner batch + realtime)",
        goal="Ngăn listing marketing sai lệch so với Golden Record trước khi public",
        trigger="Listing submit review hoặc scheduled drift rescan",
        pre="Listing PENDING_REVIEW hoặc FLAGGED; GR version hiện tại accessible",
        post="APPROVED (publish queue) hoặc REJECTED/BLOCKED với reason audit",
        priority="P0 Must",
        trace="FR-GR-04, FR-GR-05 · BR-09, BR-10",
        api="GET /moderation/queue · POST /listings/{id}/approve|reject · GET drift-report",
        prototype="/admin/moderation · /uc/UC-GR-03",
        main=[
            [1, "Ops mở ModerationQueue — filter PENDING + DRIFT_FLAG"],
            [2, "Side-by-side: GR snapshot vs listing fields (giá, m², pháp lý, hình ảnh watermark)"],
            [3, "DriftPanel: severity BLOCK/WARN + rule id triggered"],
            [4, "Ops preview public page mock — Verified badge preview BR-10"],
            [5, "Approve → publish index OpenSearch + SSE unit status UC-GR-07"],
            [6, "Reject/Block → notify agent + lý do bắt buộc; audit FR-TR-01"],
        ],
        alt=[
            ["E1", "BLOCK severity → không có nút Approve — chỉ Reject hoặc request agent fix"],
            ["E2", "GR thay đổi sau submit → re-run drift; listing auto-FLAG"],
            ["E3", "Bulk approve batch ≤20 với cùng project policy"],
        ],
        io_in="listingId, decision, rejectReason, opsNote",
        io_out="listing status, publish event, audit entry",
        rules=["BR-01", "BR-09", "BR-10", "BR-08"],
    ),
    "UC-GR-04": uc_detail(
        "UC-GR-04",
        "Xem Product Graph & quan hệ unit",
        screens="SCR-DEV-010",
        actor="Developer Admin",
        goal="Navigate cấu trúc Project → Building → Floor → Unit và quan hệ phụ thuộc",
        trigger="Developer cần overview inventory hoặc drill-down unit cluster",
        pre="Project graph seeded; cap gr.graph.read",
        post="Graph rendered; click unit → deep link SCR-DEV-012 với filter",
        priority="P0 Must",
        trace="FR-GR-01",
        api="GET /api/v1/projects/{id}/graph · GET /units?buildingId=",
        prototype="/developer/product-graph · /uc/UC-GR-04",
        main=[
            [1, "Load ProductGraph — root node Project với KPI sold/available"],
            [2, "Expand Building nodes — color by absorption rate"],
            [3, "Expand Floor → Unit leaves — status chip (AVAILABLE, RESERVED, SOLD)"],
            [4, "Click unit leaf → navigate /developer/units?unitId= highlight row"],
            [5, "Filter graph: tower, price band, status"],
            [6, "Export PNG graph snapshot (optional P1)"],
        ],
        alt=[
            ["E1", "Graph stale >5min → banner refresh từ GR API"],
            ["E2", "Large project >500 units → lazy load floor level"],
        ],
        io_in="projectId, filters{building, status}",
        io_out="graph JSON nodes/edges + navigation deep link",
        rules=["BR-01"],
    ),
    "UC-GR-07": uc_detail(
        "UC-GR-07",
        "Real-time push trạng thái unit (SSE)",
        screens="SCR-SYS-002",
        actor="System (SSE broker)",
        actor_secondary="All portals subscribe (Public, Agent, Developer)",
        goal="Mọi portal thấy trạng thái unit cập nhật ≤5s sau thay đổi GR/booking",
        trigger="Domain event UnitStatusChanged | BookingLockAcquired | BookingReleased",
        pre="Redis pub/sub bridge active; client SSE connection authenticated (public anonymous OK cho published units)",
        post="Connected clients invalidate cache + UI badge update; search lag ≤5s BR-20",
        priority="P0 Must",
        trace="FR-GR-08, FR-LS-06 · BR-20",
        api="GET /api/v1/sse/units · POST internal publish · CDC outbox",
        prototype="System — prototype mock SSE toast on unit detail",
        main=[
            [1, "GR/Booking service emit UnitStatusChanged vào outbox"],
            [2, "Worker consume → Redis channel unit:{tenantId}:{unitId}"],
            [3, "SSE gateway push event {unitId, status, version, ts} tới subscribers"],
            [4, "Public unit detail + search card cập nhật badge AVAILABLE/RESERVED"],
            [5, "Agent listing wizard disable unit nếu RESERVED mid-session"],
            [6, "Metrics: p95 delivery latency ≤5s NFR-P04"],
        ],
        alt=[
            ["E1", "SSE disconnect → client exponential backoff reconnect"],
            ["E2", "Missed events → fallback GET /units/{id} on focus"],
            ["E3", "Tenant isolation — subscriber chỉ nhận events tenant scope"],
        ],
        io_in="domain event payload: unitId, oldStatus, newStatus, actor, bookingId?",
        io_out="SSE message + CDN cache purge + OpenSearch partial update",
        rules=["BR-03", "BR-20"],
    ),
}
