"""Deep SCR UI/API overrides — P0 CRM, Listing & Search, Identity."""
from __future__ import annotations

from wereal_ba_detail_helpers import scr_detail

P0_CRM_LS_ID_SCREEN_DETAILS: dict[str, dict] = {
    "SCR-PUBLIC-005": scr_detail(
        "SCR-PUBLIC-005",
        "Tìm kiếm & lọc sản phẩm BĐS",
        route="/public/search",
        module="MOD-PUBLIC — Listing & Search",
        purpose="Guest/Buyer search OpenSearch với facet, sort, verified filter",
        roles="Buyer, Guest",
        linked_ucs="UC-LS-01",
        app="Public Portal",
        trace="FR-LS-02, FR-LS-06",
        api="GET /search/units · GET /search/suggest",
        ui=[
            [1, "PublicHeader", "Navigation", "Có", "Logo · Search shortcut · Login"],
            [2, "SearchQueryBar", "Search", "Có", "Autocomplete suggest debounce"],
            [3, "FacetSidebar", "Filter", "Có", "Bedrooms, price, district, verified"],
            [4, "SortDropdown", "Select", "Có", "Price, newest, relevance"],
            [5, "ResultsGrid", "CardGrid", "Có", "Thumbnail, price, verified, status SSE"],
            [6, "CompareTray", "Floating", "Không", "UC-LS-03 compare up to 3"],
            [7, "Pagination", "Pager", "Có", "Infinite scroll mobile"],
        ],
        rules=["BR-10", "BR-20", "BR-09"],
    ),
    "SCR-PUBLIC-006": scr_detail(
        "SCR-PUBLIC-006",
        "Chi tiết unit + Lead form",
        route="/public/units/un_01",
        module="MOD-PUBLIC + MOD-CRM",
        purpose="Unit detail trust-first + sticky lead capture UC-CRM-01",
        roles="Buyer, Guest",
        linked_ucs="UC-LS-05, UC-CRM-01",
        app="Public Portal",
        trace="FR-UX-01, FR-CRM-01",
        api="GET /listings/{id} · GET /units/{id} · POST /leads · SSE /sse/units",
        ui=[
            [1, "MediaGallery", "Carousel", "Có", "Swipe + lightbox fullscreen"],
            [2, "VerifiedBadge", "Badge", "Có", "Green shield + tooltip GR source"],
            [3, "SpecTable", "Table", "Có", "Area, legal, orientation — GR synced"],
            [4, "PriceDisplay", "Typography", "Có", "Tabular nums · price history hidden public"],
            [5, "StatusLiveChip", "Badge", "Có", "SSE AVAILABLE/RESERVED"],
            [6, "StickyLeadForm", "Form", "Có", "Name, phone, consent PDPA, submit"],
            [7, "ThankYouModal", "Modal", "Có", "Post-submit confirmation"],
        ],
        rules=["BR-10", "BR-15", "BR-07"],
    ),
    "SCR-AGENT-010": scr_detail(
        "SCR-AGENT-010",
        "Upload media listing",
        route="/agent/listings/media",
        module="MOD-LS — Listing media",
        purpose="Presigned upload, virus scan, gallery ordering",
        roles="Agent",
        linked_ucs="UC-LS-04",
        app="Agent Portal",
        trace="FR-LS-03",
        api="POST /media/presign · POST /media/attach · scan webhook",
        ui=[
            [1, "ListingContextBar", "Header", "Có", "Listing draft ref + back wizard"],
            [2, "MediaDropzone", "Upload", "Có", "Drag-drop multi-file progress"],
            [3, "GalleryReorder", "Sortable", "Có", "Set cover star icon"],
            [4, "ScanStatusBadge", "Badge", "Có", "PENDING | CLEAN | QUARANTINE"],
            [5, "VideoUploadSlot", "Upload", "Không", "Max 1 video optional"],
            [6, "SaveContinue", "Button", "Có", "Return to listing wizard step"],
        ],
        rules=["BR-09"],
    ),
    "SCR-AGENT-014": scr_detail(
        "SCR-AGENT-014",
        "CRM Pipeline Kanban",
        route="/agent/pipeline",
        module="MOD-CRM",
        purpose="Kanban lead stages + activity logging + booking shortcut",
        roles="Agent",
        linked_ucs="UC-CRM-03",
        app="Agent Portal",
        trace="FR-CRM-04, FR-CRM-05",
        api="GET /leads · PATCH /leads/{id} · POST activities",
        ui=[
            [1, "PipelineKanban", "Kanban", "Có", "6 columns drag-drop"],
            [2, "LeadCard", "Card", "Có", "HOT badge, unit, SLA timer, owner avatar"],
            [3, "QuickActivityLog", "Popover", "Có", "Call / note / visit one-click"],
            [4, "LeadDetailDrawer", "Drawer", "Có", "Full timeline + AI score UC-AI-02"],
            [5, "CreateBookingCTA", "Button", "Có", "→ UC-BK-01 prefilled lead+unit"],
            [6, "PipelineFilters", "Filter", "Có", "My · Hot · Project · Overdue"],
        ],
        rules=["BR-12", "BR-07", "BR-08"],
    ),
    "SCR-AGENT-015": scr_detail(
        "SCR-AGENT-015",
        "Lead routing settings",
        route="/agent/settings/routing",
        module="MOD-CRM",
        purpose="Configure round-robin, HOT override, manual assign rules",
        roles="Agency Admin",
        linked_ucs="UC-CRM-02",
        app="Agent Portal",
        trace="FR-CRM-03",
        api="GET/PATCH /crm/routing-rules · POST /leads/{id}/assign",
        ui=[
            [1, "RoutingPoolList", "List", "Có", "Per project / default pool"],
            [2, "StrategySelector", "Radio", "Có", "Round-robin | Territory | Manual"],
            [3, "HotScoreThreshold", "Slider", "Có", "Default 80 → senior agent BR-07"],
            [4, "AgentPoolPicker", "MultiSelect", "Có", "Active agents only"],
            [5, "RuleVersionHistory", "Timeline", "Không", "Audit policy changes"],
            [6, "SaveRoutingRules", "Button", "Có", "Apply to PENDING leads option"],
        ],
        rules=["BR-07"],
    ),
    "SCR-AUTH-001": scr_detail(
        "SCR-AUTH-001",
        "Đăng nhập đa portal",
        route="/auth/login",
        module="MOD-ID — Authentication",
        purpose="Email/password login, tenant picker, MFA step-up entry",
        roles="All users",
        linked_ucs="UC-ID-03",
        app="Auth — shared entry",
        trace="FR-ID-04, CON-10",
        api="POST /auth/login · POST /auth/refresh · POST /auth/mfa/verify",
        ui=[
            [1, "LoginForm", "Form", "Có", "Email, password, show/hide toggle"],
            [2, "TenantSelector", "Select", "Không", "If user belongs >1 tenant"],
            [3, "ForgotPasswordLink", "Link", "Có", "P1 self-serve reset"],
            [4, "MfaOtpModal", "Modal", "Có", "6-digit OTP step-up BR-14"],
            [5, "BruteForceAlert", "Alert", "Có", "Lock message after 5 fails"],
            [6, "PortalRedirect", "Router", "Có", "Post-login by role claim"],
        ],
        rules=["BR-14"],
    ),
    "SCR-ADMIN-019": scr_detail(
        "SCR-ADMIN-019",
        "Onboard tenant wizard",
        route="/admin/tenants/onboard",
        module="MOD-ID — Tenant",
        purpose="Platform Admin tạo Developer/Agency tenant + invite admin",
        roles="Platform Admin",
        linked_ucs="UC-ID-01",
        app="Admin / Ops Portal",
        trace="FR-ID-01, CON-13",
        api="POST /tenants · POST /users/invite · POST /tenants/{id}/activate",
        ui=[
            [1, "OnboardWizardStepper", "Stepper", "Có", "3 steps: Info · Plan · Admin invite"],
            [2, "TenantTypeToggle", "Radio", "Có", "DEVELOPER | AGENCY"],
            [3, "SlugValidator", "Input", "Có", "Realtime unique check"],
            [4, "ModuleFlagsChecklist", "Checkbox", "Có", "Phase 1 module scope"],
            [5, "AdminInviteForm", "Form", "Có", "Primary admin email"],
            [6, "ActivateTenantButton", "Button", "Có", "Pilot UAT gate BR-25"],
        ],
        rules=["BR-25"],
    ),
    "SCR-ADMIN-020": scr_detail(
        "SCR-ADMIN-020",
        "Quản lý user tenant",
        route="/admin/users",
        module="MOD-ID — IAM",
        purpose="Invite, role assign, deactivate users trong tenant",
        roles="Agency Admin, Developer Admin",
        linked_ucs="UC-ID-04",
        app="Admin Portal (tenant-scoped)",
        trace="FR-ID-02",
        api="GET/POST /users · PATCH /users/{id} · POST invite",
        ui=[
            [1, "UserTable", "Table", "Có", "Name, email, role, status, lastLogin"],
            [2, "InviteUserModal", "Modal", "Có", "Email + role + project scope"],
            [3, "RoleAssignDropdown", "Select", "Có", "Inline edit permitted roles"],
            [4, "DeactivateConfirm", "Dialog", "Có", "Reassign leads warning"],
            [5, "SeatUsageMeter", "Progress", "Không", "Plan quota indicator"],
            [6, "UserAuditLink", "Link", "Có", "→ audit filtered by userId"],
        ],
        rules=["BR-08"],
    ),
    "SCR-ADMIN-021": scr_detail(
        "SCR-ADMIN-021",
        "RBAC / ABAC policy editor",
        route="/admin/users/roles",
        module="MOD-ID — IAM",
        purpose="Permission matrix + project scope — deny GR write for agents",
        roles="Agency Admin, Developer Admin, Platform Admin",
        linked_ucs="UC-ID-02",
        app="Admin Portal",
        trace="FR-ID-02, CON-09",
        api="GET/PATCH /roles · policy engine API",
        ui=[
            [1, "RoleListSidebar", "List", "Có", "Built-in + custom roles"],
            [2, "PermissionMatrix", "Grid", "Có", "Module × read/write/admin toggles"],
            [3, "AbacProjectScope", "MultiSelect", "Có", "Limit role to projectIds"],
            [4, "DenyRulePanel", "Alert", "Có", "Highlight gr.units.write deny Agent"],
            [5, "EffectivePreview", "Panel", "Có", "Simulate user caps"],
            [6, "SavePolicy", "Button", "Có", "Version bump + cache invalidate"],
        ],
        rules=["BR-01"],
    ),
    "SCR-SYS-003": scr_detail(
        "SCR-SYS-003",
        "Search index CDC worker",
        route="/uc/UC-LS-07",
        module="MOD-LS — Infrastructure",
        purpose="Outbox → OpenSearch sync ≤5s — monitoring only UI",
        roles="System, DevOps",
        linked_ucs="UC-LS-07",
        app="NestJS worker + OpenSearch",
        trace="FR-LS-06, FR-GR-08",
        api="Outbox consumer · OpenSearch bulk · internal metrics",
        status_note="Draft — infra component",
        ui=[
            [1, "OutboxLagChart", "Chart", "Có", "p50/p95 lag ms"],
            [2, "BulkIndexLog", "Log", "Có", "Last 100 operations tenant-scoped"],
            [3, "DlqQueuePanel", "Table", "Có", "Failed events retry"],
            [4, "ReindexTrigger", "Button", "Không", "Manual reindex admin only"],
        ],
        rules=["BR-20", "BR-09"],
    ),
    # Override batch-1 moderation screen to cover LS-02 publish + GR-03 drift
    "SCR-ADMIN-016": scr_detail(
        "SCR-ADMIN-016",
        "Moderation — drift + publish review",
        route="/admin/moderation",
        module="MOD-GR + MOD-LS",
        purpose="Ops queue: anti-drift (UC-GR-03) + publish approval (UC-LS-02)",
        roles="Ops Admin, Platform Admin",
        linked_ucs="UC-GR-03, UC-LS-02",
        app="Admin / Ops Portal",
        trace="FR-GR-04, FR-LS-01, FR-GR-05",
        api="GET moderation/queue · PATCH approve/reject · drift-report · publish-index",
        notes="Shared screen batch-1 GR + batch-2 LS publish tab",
        ui=[
            [1, "ModerationTabBar", "Tabs", "Có", "Drift review · Publish review · Duplicates P2"],
            [2, "ModerationQueueTable", "Table", "Có", "Filter PENDING, DRIFT_FLAG"],
            [3, "SplitCompareView", "Panel", "Có", "GR vs Listing side-by-side UC-GR-03"],
            [4, "DriftSeverityBadge", "Badge", "Có", "BLOCK | WARN"],
            [5, "PublishPreviewPanel", "Panel", "Có", "Public page mock UC-LS-02"],
            [6, "ApprovePublishButton", "Button", "Có", "Triggers OpenSearch index UC-LS-07"],
            [7, "RejectReasonForm", "Form", "Có", "Required on reject — notify agent"],
        ],
        rules=["BR-09", "BR-10", "BR-01", "BR-20"],
    ),
}
